// context/ButtonContext.tsx
import { ThemeKey, useTheme } from './ThemeContext';
import { ViewStyle } from 'react-native';

interface ThemeButtonStyle {
  addButton: ViewStyle;
  addButtonLong: ViewStyle;
  themeToggle: ViewStyle;
  themeToggleActive: ViewStyle;
  headerBtn: ViewStyle;
  signOutBtn: ViewStyle;
  iconWrapper: ViewStyle;
}

export const themeButtonStyles: Record<ThemeKey, ThemeButtonStyle> = {
  nostalgia: {
    addButton: {
      borderRadius: 14,
      borderColor: '#8ee8b4',
      borderWidth: 1.5,
      shadowColor: 'rgba(126, 200, 160, 0.6)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 20,
      shadowOpacity: 1,
      elevation: 8,
    },
    addButtonLong: {
      borderRadius: 20,
    },
    themeToggle: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(142, 232, 180, 0.2)',
      backgroundColor: 'rgba(15, 30, 20, 0.35)',
    },
    themeToggleActive: {
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: '#8ee8b4',
      backgroundColor: 'rgba(88, 176, 122, 0.45)',
      shadowColor: '#7EC8A0',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 14,
      shadowOpacity: 1,
      elevation: 8,
    },
    headerBtn: {
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: '#d2b478',
      backgroundColor: 'rgba(50, 30, 8, 0.7)',
      shadowColor: '#a0783c',
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 8,
      shadowOpacity: 0.8,
      elevation: 5,
      padding: 7,
    },
    signOutBtn: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#b48c50',
      borderLeftWidth: 3,
      borderLeftColor: '#d2b478',
      backgroundColor: 'rgba(45, 22, 5, 0.72)',
      shadowColor: '#a0783c',
      shadowOffset: { width: 2, height: 2 },
      shadowRadius: 0,
      shadowOpacity: 0.6,
      elevation: 3,
    },
    iconWrapper: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.5)',
      borderLeftWidth: 3,
      borderLeftColor: '#d2b478',
      backgroundColor: 'rgba(45, 22, 5, 0.7)',
      shadowColor: '#a0783c',
      shadowOffset: { width: 3, height: 3 },
      shadowRadius: 0,
      shadowOpacity: 0.7,
      elevation: 5,
    },
  },

  refreshing: {
    addButton: {
      borderRadius: 99,
      borderColor: 'rgba(224, 250, 255, 0.25)',
      borderWidth: 1.5,
      shadowColor: 'rgba(92, 225, 230, 0.4)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 40,
      shadowOpacity: 1,
      elevation: 6,
    },
    addButtonLong: {
      borderRadius: 15,
      borderColor: 'rgba(170, 224, 234, 0.69)',
      borderWidth: 1.5,
    },
    themeToggle: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.15)',
      backgroundColor: 'rgba(224, 250, 255, 0.03)',
    },
    themeToggleActive: {
      borderRadius: 99,
      borderWidth: 1.5,
      borderColor: '#5ce1e6',
      backgroundColor: 'rgba(92, 225, 230, 0.35)',
      shadowColor: '#5ce1e6',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 18,
      shadowOpacity: 1,
      elevation: 8,
    },
    headerBtn: {
      borderRadius: 99,
      borderWidth: 1.5,
      borderColor: '#a3f7f5',
      backgroundColor: 'rgba(20, 110, 130, 0.5)',
      shadowColor: '#00e5ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 12,
      shadowOpacity: 0.5,
      elevation: 5,
      padding: 7,
    },
    signOutBtn: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.45)',
      borderRightWidth: 3,
      borderRightColor: '#00f5ff',
      backgroundColor: 'rgba(8, 45, 55, 0.7)',
      shadowColor: '#00e5ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 10,
      shadowOpacity: 0.3,
      elevation: 3,
    },
    iconWrapper: {
      borderRadius: 99,
      borderWidth: 1.5,
      borderColor: 'rgba(92, 225, 230, 0.5)',
      borderRightWidth: 4,
      borderRightColor: '#00f5ff',
      backgroundColor: 'rgba(8, 45, 55, 0.7)',
      shadowColor: '#00e5ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 16,
      shadowOpacity: 0.4,
      elevation: 5,
    },
  },

  love: {
    addButton: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomLeftRadius: 6,
      borderColor: '#fff0f6',
      borderWidth: 1.5,
      shadowColor: 'rgba(255, 96, 144, 0.4)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 36,
      shadowOpacity: 1,
      elevation: 10,
    },
    addButtonLong: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomLeftRadius: 6,
      borderColor: '#fff0f6',
      borderWidth: 1.5,
    },
    themeToggle: {
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderBottomRightRadius: 18,
      borderBottomLeftRadius: 5,
      borderWidth: 1,
      borderColor: 'rgba(255, 182, 210, 0.2)',
      backgroundColor: 'rgba(30, 5, 15, 0.4)',
    },
    themeToggleActive: {
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderBottomRightRadius: 18,
      borderBottomLeftRadius: 5,
      borderWidth: 1.5,
      borderColor: '#ff6090',
      backgroundColor: 'rgba(255, 96, 144, 0.4)',
      shadowColor: 'rgba(255, 60, 120, 0.7)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 16,
      shadowOpacity: 1,
      elevation: 10,
    },
    headerBtn: {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      borderBottomLeftRadius: 4,
      borderWidth: 1.5,
      borderColor: '#ff69b4',
      backgroundColor: 'rgba(80, 10, 40, 0.7)',
      shadowColor: '#ff007f',
      shadowOffset: { width: 3, height: 3 },
      shadowRadius: 0,
      shadowOpacity: 1,
      elevation: 6,
      padding: 7,
    },
    signOutBtn: {
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: '#ff69b4',
      borderBottomColor: '#ff007f',
      backgroundColor: 'rgba(255, 100, 160, 0.55)',
      shadowColor: '#ff007f',
      shadowOffset: { width: 3, height: 3 },
      shadowRadius: 0,
      shadowOpacity: 0.8,
      elevation: 4,
    },
    iconWrapper: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderBottomRightRadius: 28,
      borderBottomLeftRadius: 6,
      borderWidth: 1.5,
      borderColor: '#ff69b4',
      borderBottomColor: '#ff007f',
      backgroundColor: 'rgba(50, 5, 22, 0.7)',
      shadowColor: '#ff007f',
      shadowOffset: { width: 4, height: 4 },
      shadowRadius: 0,
      shadowOpacity: 0.9,
      elevation: 6,
    },
  },

  cheerful: {
    addButton: {
      borderRadius: 14,
      borderColor: '#fff176',
      borderWidth: 1.5,
      shadowColor: 'rgba(255, 220, 50, 0.85)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 32,
      shadowOpacity: 1,
      elevation: 12,
    },
    addButtonLong: {
      borderRadius: 14,
      borderColor: '#fff176',
      borderWidth: 1.5,
    },
    themeToggle: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 220, 50, 0.2)',
      backgroundColor: 'rgba(20, 12, 0, 0.4)',
    },
    themeToggleActive: {
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: '#ffe000',
      backgroundColor: 'rgba(255, 210, 0, 0.4)',
      shadowColor: 'rgba(255, 220, 50, 0.9)',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 18,
      shadowOpacity: 1,
      elevation: 12,
    },
    headerBtn: {
      borderRadius: 10,
      borderWidth: 2,
      borderColor: '#000000',
      backgroundColor: 'rgba(200, 140, 0, 0.75)',
      shadowColor: '#ff4d00',
      shadowOffset: { width: 4, height: 4 },
      shadowRadius: 0,
      shadowOpacity: 1,
      elevation: 6,
      padding: 7,
    },
    signOutBtn: {
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 210, 0, 0.6)',
      borderBottomWidth: 3,
      borderBottomColor: 'rgba(255, 160, 0, 0.8)',
      backgroundColor: 'rgba(255, 210, 0, 0.55)',
      shadowColor: '#ff4d00',
      shadowOffset: { width: 4, height: 4 },
      shadowRadius: 0,
      shadowOpacity: 0.9,
      elevation: 4,
    },
    iconWrapper: {
      borderRadius: 16,
      borderWidth: 2,
      borderColor: '#000000',
      backgroundColor: 'rgba(200, 140, 0, 0.65)',
      shadowColor: '#ff4d00',
      shadowOffset: { width: 6, height: 6 },
      shadowRadius: 0,
      shadowOpacity: 1,
      elevation: 6,
    },
  },

  emo: {
    addButton: {
      borderRadius: 6,
      borderColor: '#3a3a3a',
      borderWidth: 1,
      backgroundColor: 'transparent',
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 14,
      shadowOpacity: 1,
      elevation: 4,
    },
    addButtonLong: {
      borderRadius: 6,
      borderColor: '#3a3a3a',
      borderWidth: 1,
      backgroundColor: 'transparent',
    },
    themeToggle: {
      borderRadius: 6,
      borderWidth: 1,
      borderColor: '#242424',
      backgroundColor: 'rgba(8, 8, 8, 0.6)',
    },
    themeToggleActive: {
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: '#8a6aaa',
      backgroundColor: 'rgba(90, 70, 120, 0.4)',
      shadowColor: 'rgba(110, 85, 160, 0.65)',
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 12,
      shadowOpacity: 1,
      elevation: 6,
    },
    headerBtn: {
      borderRadius: 4,
      borderWidth: 1,
      borderLeftWidth: 3,
      borderColor: '#101428',
      borderLeftColor: '#4895ef',
      backgroundColor: 'rgba(8, 10, 25, 0.85)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      shadowOpacity: 0.6,
      elevation: 5,
      padding: 7,
    },
    signOutBtn: {
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#101428',
      borderLeftWidth: 4,
      borderLeftColor: '#4895ef',
      backgroundColor: 'rgba(3, 4, 14, 0.88)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      shadowOpacity: 0.7,
      elevation: 4,
    },
    iconWrapper: {
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#101428',
      borderLeftWidth: 5,
      borderLeftColor: '#4895ef',
      backgroundColor: 'rgba(3, 4, 14, 0.88)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      shadowOpacity: 0.7,
      elevation: 5,
    },
  },

  aspire: {
    addButton: {
      borderRadius: 99,
      borderColor: '#a0f0ff',
      borderWidth: 1.5,
      shadowColor: '#00d2ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 26,
      shadowOpacity: 0.85,
      elevation: 12,
    },
    addButtonLong: {
      borderRadius: 30,
      borderColor: '#a0f1ff1e',
      borderWidth: 1.5,
      shadowColor: '#00d2ff',
    },
    themeToggle: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: 'rgba(160, 240, 255, 0.15)',
      backgroundColor: 'rgba(5, 3, 20, 0.5)',
    },
    themeToggleActive: {
      borderRadius: 99,
      borderWidth: 1.5,
      borderColor: '#a0f0ff',
      backgroundColor: 'rgba(0, 180, 255, 0.35)',
      shadowColor: '#00d2ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 20,
      shadowOpacity: 1,
      elevation: 12,
    },
    headerBtn: {
      borderRadius: 99,
      borderWidth: 1.5,
      borderColor: '#00b4d8',
      borderBottomColor: '#ff9e00',
      borderBottomWidth: 2,
      backgroundColor: 'rgba(12, 28, 85, 0.72)',
      shadowColor: '#4361ee',
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 12,
      shadowOpacity: 0.65,
      elevation: 7,
      padding: 7,
    },
    signOutBtn: {
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: '#7b2ff7',
      backgroundColor: 'rgba(30, 0, 75, 0.75)',
      shadowColor: '#7b2ff7',
      shadowOffset: { width: 0, height: -3 },
      shadowRadius: 10,
      shadowOpacity: 0.6,
      elevation: 4,
    },
    iconWrapper: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
      borderBottomRightRadius: 28,
      borderWidth: 1,
      borderColor: '#7b2ff7',
      backgroundColor: 'rgba(30, 0, 75, 0.75)',
      shadowColor: '#7b2ff7',
      shadowOffset: { width: 0, height: -4 },
      shadowRadius: 16,
      shadowOpacity: 0.7,
      elevation: 6,
    },
  },

  determination: {
    addButton: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      borderColor: '#ff9060',
      borderWidth: 1.5,
      borderTopWidth: 2.5,
      shadowColor: 'rgba(255, 107, 53, 0.65)',
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 22,
      shadowOpacity: 1,
      elevation: 10,
    },
    addButtonLong: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      borderColor: '#ff9060',
      borderWidth: 1.5,
      borderTopWidth: 2.5,
    },
    themeToggle: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderTopWidth: 2,
      borderColor: 'rgba(255, 107, 53, 0.2)',
      backgroundColor: 'rgba(10, 5, 0, 0.45)',
    },
    themeToggleActive: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1.5,
      borderTopWidth: 2.5,
      borderColor: '#ff6b35',
      backgroundColor: 'rgba(255, 107, 53, 0.4)',
      shadowColor: 'rgba(255, 107, 53, 0.8)',
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 16,
      shadowOpacity: 1,
      elevation: 10,
    },
    headerBtn: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderTopWidth: 3,
      borderColor: 'rgba(60, 20, 0, 0.5)',
      borderTopColor: '#ff5500',
      backgroundColor: 'rgba(40, 15, 0, 0.75)',
      shadowColor: '#ff4500',
      shadowOffset: { width: 0, height: 5 },
      shadowRadius: 14,
      shadowOpacity: 0.45,
      elevation: 7,
      padding: 7,
    },
    signOutBtn: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderTopWidth: 2.5,
      borderTopColor: '#ff5500',
      borderColor: 'rgba(58, 13, 0, 0.6)',
      backgroundColor: 'rgba(35, 10, 0, 0.78)',
      shadowColor: '#ff4500',
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      shadowOpacity: 0.35,
      elevation: 4,
    },
    iconWrapper: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderWidth: 1,
      borderTopWidth: 3,
      borderTopColor: '#ff5500',
      borderColor: 'rgba(58, 13, 0, 0.7)',
      backgroundColor: 'rgba(35, 10, 0, 0.75)',
      shadowColor: '#ff4500',
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 14,
      shadowOpacity: 0.45,
      elevation: 6,
    },
  },

  wrath: {
    addButton: {
      borderRadius: 0,
      borderColor: '#8b0000',
      borderWidth: 1,
      shadowColor: 'rgba(180, 0, 0, 0.6)',
      shadowOffset: { width: 4, height: 0 },
      shadowRadius: 24,
      shadowOpacity: 1,
      elevation: 10,
    },
    addButtonLong: {
      borderRadius: 0,
      borderColor: '#8b0000',
      borderWidth: 1,
    },
    themeToggle: {
      borderRadius: 0,
      borderWidth: 1,
      borderColor: 'rgba(139, 0, 0, 0.3)',
      backgroundColor: 'rgba(10, 0, 0, 0.55)',
    },
    themeToggleActive: {
      borderRadius: 0,
      borderWidth: 1,
      borderLeftWidth: 3,
      borderColor: 'rgba(204, 0, 0, 0.8)',
      borderLeftColor: '#ff0000',
      backgroundColor: 'rgba(140, 0, 0, 0.45)',
      shadowColor: 'rgba(200, 0, 0, 0.8)',
      shadowOffset: { width: 4, height: 0 },
      shadowRadius: 18,
      shadowOpacity: 1,
      elevation: 10,
    },
    headerBtn: {
      borderRadius: 1,
      borderWidth: 1,
      borderLeftWidth: 5,
      borderColor: 'rgba(43, 0, 0, 0.6)',
      borderLeftColor: '#660708',
      backgroundColor: 'rgba(18, 0, 0, 0.82)',
      shadowColor: '#ba181b',
      shadowOffset: { width: -4, height: 4 },
      shadowRadius: 10,
      shadowOpacity: 0.85,
      elevation: 8,
      padding: 7,
    },
    signOutBtn: {
      borderRadius: 1,
      borderWidth: 1,
      borderLeftWidth: 5,
      borderColor: 'rgba(43, 0, 0, 0.6)',
      borderLeftColor: '#660708',
      backgroundColor: 'rgba(18, 0, 0, 0.82)',
      shadowColor: '#ba181b',
      shadowOffset: { width: -4, height: 3 },
      shadowRadius: 10,
      shadowOpacity: 0.75,
      elevation: 5,
    },
    iconWrapper: {
      borderRadius: 1,
      borderWidth: 1,
      borderLeftWidth: 6,
      borderColor: 'rgba(43, 0, 0, 0.6)',
      borderLeftColor: '#660708',
      backgroundColor: 'rgba(18, 0, 0, 0.82)',
      shadowColor: '#ba181b',
      shadowOffset: { width: -5, height: 5 },
      shadowRadius: 12,
      shadowOpacity: 0.85,
      elevation: 7,
    },
  },
};

export const ADD_BUTTON_GRADIENTS: Record<ThemeKey, [string, string, ...string[]]> = {
  nostalgia:     ['#3a7a52', '#5ab07a'],
  refreshing:    [
    'rgba(48, 181, 255, 0.70)',
    'rgba(92, 225, 230, 0.35)',
    'rgba(196, 250, 252, 0.57)'
  ],
  love:          ['#ff3377', '#ff8ebb', '#ff5599'],
  cheerful:      ['#ffaa00', '#ffe000', '#ffcc00'],
  emo:           ['#1a1a1a', '#2e2e2e'],
  aspire:        ['#0b0926', '#13409b', '#00bcd4', '#00e5ff', '#ffffff'],
  determination: ['#c03000', '#ff5500'],
  wrath:         ['#1a0000', '#3d0000'],
};

export function useButtonTheme() {
  const { activeTheme } = useTheme();
  const ThemeButtonStyles = themeButtonStyles[activeTheme] ?? themeButtonStyles.aspire;
  return { ThemeButtonStyles, activeTheme };
}