// context/ModalContext.tsx
import { useTheme, ThemeKey } from './ThemeContext';
import { ViewStyle, TextStyle } from 'react-native';

interface ThemeModalStyle {
  modal: ViewStyle;
  modalTitle: TextStyle;
  label: TextStyle;
  input: TextStyle;
  themeChip: ViewStyle;
  themeChipSelected: ViewStyle;
  themeChipText: TextStyle;
  themeChipTextSelected: TextStyle;
  cancelButton: ViewStyle;
  cancelText: TextStyle;
  saveButton: ViewStyle;
  saveText: TextStyle;
  uploadButton: ViewStyle;   // LyricsEditForm only
  deleteButton: ViewStyle;   // LyricsEditForm only
  deleteText: TextStyle;
}

const themeModalStyles: Record<ThemeKey, ThemeModalStyle> = {
  nostalgia: {
    modal: {
      borderTopLeftRadius: 4,
      borderTopRightRadius: 20,
      borderBottomRightRadius: 4,
      borderBottomLeftRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.4)',
      borderLeftWidth: 3,
      borderLeftColor: '#d2b478',
      backgroundColor: 'rgba(28, 14, 4, 0.97)',
      shadowColor: '#a0783c',
      shadowOffset: { width: 3, height: 3 },
      shadowRadius: 0,
      shadowOpacity: 0.7,
      elevation: 8,
    },
    modalTitle: {
      color: '#ffd699',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(210, 180, 120, 0.65)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(255, 220, 160, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.3)',
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#ffd699',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.3)',
      backgroundColor: 'rgba(255, 220, 160, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#d2b478',
      borderColor: '#d2b478',
    },
    themeChipText: {
      color: 'rgba(210, 180, 120, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#000000',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(210, 180, 120, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: '#d2b478',
      alignItems: 'center',
    },
    saveText: {
      color: '#000000',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(255, 220, 160, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(210, 180, 120, 0.3)',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  refreshing: {
    modal: {
      borderRadius: 24,
      borderWidth: 1.5,
      borderColor: 'rgba(92, 225, 230, 0.45)',
      borderRightWidth: 4,
      borderRightColor: '#00f5ff',
      backgroundColor: 'rgba(8, 30, 38, 0.97)',
      shadowColor: '#00e5ff',
      shadowOffset: { width: 0, height: 0 },
      shadowRadius: 20,
      shadowOpacity: 0.35,
      elevation: 8,
    },
    modalTitle: {
      color: '#e8feff',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(92, 225, 230, 0.6)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(92, 225, 230, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.3)',
      borderRadius: 99,
      paddingHorizontal: 16,
      paddingVertical: 8,
      color: '#e8feff',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 99,
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.3)',
      backgroundColor: 'rgba(92, 225, 230, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#5ce1e6',
      borderColor: '#5ce1e6',
    },
    themeChipText: {
      color: 'rgba(92, 225, 230, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#003d40',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 99,
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(92, 225, 230, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 99,
      backgroundColor: '#5ce1e6',
      alignItems: 'center',
    },
    saveText: {
      color: '#003d40',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(92, 225, 230, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(92, 225, 230, 0.3)',
      borderRadius: 99,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderRadius: 99,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  love: {
    modal: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
      borderBottomLeftRadius: 4,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 105, 180, 0.45)',
      borderBottomColor: '#ff007f',
      backgroundColor: 'rgba(28, 3, 14, 0.97)',
      shadowColor: '#ff007f',
      shadowOffset: { width: 4, height: 4 },
      shadowRadius: 0,
      shadowOpacity: 0.8,
      elevation: 8,
    },
    modalTitle: {
      color: '#ffe0ee',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(255, 150, 190, 0.65)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(255, 150, 190, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(255, 105, 180, 0.3)',
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#ffe0ee',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: 'rgba(255, 105, 180, 0.3)',
      backgroundColor: 'rgba(255, 150, 190, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#ff69b4',
      borderColor: '#ff69b4',
    },
    themeChipText: {
      color: 'rgba(255, 150, 190, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#3d0018',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: 'rgba(255, 105, 180, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(255, 150, 190, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      backgroundColor: '#ff69b4',
      alignItems: 'center',
    },
    saveText: {
      color: '#3d0018',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(255, 150, 190, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(255, 105, 180, 0.3)',
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      borderBottomRightRadius: 14,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  cheerful: {
    modal: {
      borderRadius: 12,
      borderWidth: 2,
      borderColor: 'rgba(255, 210, 0, 0.55)',
      borderBottomWidth: 3,
      borderBottomColor: 'rgba(255, 160, 0, 0.8)',
      backgroundColor: 'rgba(22, 12, 0, 0.97)',
      shadowColor: '#ff4d00',
      shadowOffset: { width: 6, height: 5 },
      shadowRadius: 0,
      shadowOpacity: 1,
      elevation: 8,
    },
    modalTitle: {
      color: '#fff8dc',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(255, 210, 80, 0.65)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(255, 210, 0, 0.07)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 210, 0, 0.3)',
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#fff8dc',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 210, 0, 0.3)',
      backgroundColor: 'rgba(255, 210, 0, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#ffe000',
      borderColor: '#ffe000',
    },
    themeChipText: {
      color: 'rgba(255, 210, 80, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#000000',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 210, 0, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(255, 210, 80, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: '#ffe000',
      alignItems: 'center',
    },
    saveText: {
      color: '#000000',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(255, 210, 0, 0.07)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 210, 0, 0.3)',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  emo: {
    modal: {
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#101428',
      borderLeftWidth: 5,
      borderLeftColor: '#4895ef',
      backgroundColor: 'rgba(3, 4, 14, 0.98)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 12,
      shadowOpacity: 0.8,
      elevation: 8,
    },
    modalTitle: {
      color: '#e8ecff',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(120, 149, 220, 0.6)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(72, 149, 239, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(72, 149, 239, 0.25)',
      borderRadius: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#e8ecff',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: 'rgba(72, 149, 239, 0.25)',
      backgroundColor: 'rgba(72, 149, 239, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#4895ef',
      borderColor: '#4895ef',
    },
    themeChipText: {
      color: 'rgba(120, 149, 220, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#ffffff',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: 'rgba(72, 149, 239, 0.25)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(120, 149, 220, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 4,
      backgroundColor: '#4895ef',
      alignItems: 'center',
    },
    saveText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(72, 149, 239, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(72, 149, 239, 0.25)',
      borderRadius: 4,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  aspire: {
    modal: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(150, 80, 255, 0.45)',
      backgroundColor: 'rgba(8, 2, 22, 0.98)',
      shadowColor: '#7b2ff7',
      shadowOffset: { width: 0, height: -4 },
      shadowRadius: 18,
      shadowOpacity: 0.6,
      elevation: 8,
    },
    modalTitle: {
      color: '#ead6ff',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(180, 130, 255, 0.6)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(150, 80, 255, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(150, 80, 255, 0.3)',
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#ead6ff',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 3,
      borderBottomLeftRadius: 3,
      borderBottomRightRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(150, 80, 255, 0.3)',
      backgroundColor: 'rgba(150, 80, 255, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#7b2ff7',
      borderColor: '#7b2ff7',
    },
    themeChipText: {
      color: 'rgba(180, 130, 255, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#ffffff',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(150, 80, 255, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(180, 130, 255, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      backgroundColor: '#7b2ff7',
      alignItems: 'center',
    },
    saveText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(150, 80, 255, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(150, 80, 255, 0.3)',
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  determination: {
    modal: {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 22,
      borderBottomRightRadius: 22,
      borderWidth: 1,
      borderTopWidth: 3,
      borderTopColor: '#ff5500',
      borderColor: 'rgba(58, 13, 0, 0.8)',
      backgroundColor: 'rgba(10, 3, 0, 0.98)',
      shadowColor: '#ff4500',
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 20,
      shadowOpacity: 0.45,
      elevation: 8,
    },
    modalTitle: {
      color: '#ffe3cc',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(255, 140, 80, 0.65)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(255, 107, 53, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 53, 0.3)',
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#ffe3cc',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 53, 0.3)',
      backgroundColor: 'rgba(255, 107, 53, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#ff5500',
      borderColor: '#ff5500',
    },
    themeChipText: {
      color: 'rgba(255, 140, 80, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#000000',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 53, 0.35)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(255, 140, 80, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      backgroundColor: '#ff5500',
      alignItems: 'center',
    },
    saveText: {
      color: '#000000',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(255, 107, 53, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 53, 0.3)',
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },

  wrath: {
    modal: {
      borderRadius: 1,
      borderWidth: 1,
      borderLeftWidth: 6,
      borderColor: 'rgba(43, 0, 0, 0.7)',
      borderLeftColor: '#660708',
      backgroundColor: 'rgba(8, 0, 0, 0.98)',
      shadowColor: '#ba181b',
      shadowOffset: { width: -5, height: 5 },
      shadowRadius: 14,
      shadowOpacity: 0.85,
      elevation: 8,
    },
    modalTitle: {
      color: '#ffcccc',
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    label: {
      color: 'rgba(200, 80, 80, 0.65)',
      fontSize: 11,
      marginBottom: 4,
      marginTop: 8,
    },
    input: {
      backgroundColor: 'rgba(186, 24, 27, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(100, 0, 0, 0.5)',
      borderRadius: 1,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: '#ffcccc',
      fontSize: 13,
    },
    themeChip: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 1,
      borderWidth: 1,
      borderColor: 'rgba(100, 0, 0, 0.5)',
      backgroundColor: 'rgba(186, 24, 27, 0.07)',
    },
    themeChipSelected: {
      backgroundColor: '#8b0000',
      borderColor: '#8b0000',
    },
    themeChipText: {
      color: 'rgba(200, 80, 80, 0.8)',
      fontSize: 12,
    },
    themeChipTextSelected: {
      color: '#ffffff',
      fontWeight: '600',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 1,
      borderWidth: 1,
      borderColor: 'rgba(100, 0, 0, 0.5)',
      alignItems: 'center',
    },
    cancelText: {
      color: 'rgba(200, 80, 80, 0.7)',
      fontSize: 14,
    },
    saveButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 1,
      backgroundColor: '#8b0000',
      alignItems: 'center',
    },
    saveText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(186, 24, 27, 0.07)',
      borderWidth: 1,
      borderColor: 'rgba(100, 0, 0, 0.5)',
      borderRadius: 1,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    deleteButton: {
      marginTop: 10,
      paddingVertical: 10,
      borderRadius: 1,
      borderWidth: 1,
      borderColor: '#ff4444',
      alignItems: 'center',
    },
    deleteText: {
      color: '#ff4444',
      fontSize: 14,
    },
  },
};

export function useModalTheme() {
  const { activeTheme } = useTheme();
  const ThemeModalStyles = themeModalStyles[activeTheme] ?? themeModalStyles.aspire;
  return { ThemeModalStyles };
}